import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Nav from "./(site)/components/nav/Nav";
import NextTopLoader from "nextjs-toploader";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
import { Toaster } from "sonner";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth/AuthOptions";
import AuthContext from "./(site)/components/context/AuthContext";

export const metadata: Metadata = {
  title: "Todo",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={
          "bg-body w-screen h-screen flex  flex-col justify-center items-center overflow-hidden"
        }
      >
        <NextTopLoader color="#EE7C75" showSpinner={false} height={2.5} />
        <AuthContext session={session || null}>
          <main className={poppins.className}>
            <Toaster theme="dark" />

            <Nav />
          </main>
          <>{children}</>
        </AuthContext>
      </body>
    </html>
  );
}
