import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./(site)/components/context/auth";
import SigninButton from "./(site)/components/signin/Button";
import Nav from "./(site)/components/nav/Nav";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: "Todo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          "bg-body w-screen h-screen flex  flex-col justify-center items-center"
        }
      >
        <Providers>
          <main>
            <Toaster />
            <Nav />
          </main>
          <>{children}</>
        </Providers>
      </body>
    </html>
  );
}
