import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Icon from "@/public/logo.png";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={"bg-body w-screen h-screen flex justify-center items-center"}
      >
        {children}
      </body>
    </html>
  );
}
